"use client";

import { useState } from "react";
import { ClaimProfileModal } from "./ClaimProfileModal";
import { VisibilitySlider } from "@/components/VisibilitySlider";
import type { Visibility } from "@/lib/endorsement-constants";

export type RecItem = {
  id: string;
  // null when the viewer isn't allowed to see the priority text (private row,
  // non-owner viewer). Server-side scrubbing keeps the string out of the DOM.
  text: string | null;
  // null when the viewer isn't allowed to see the category either — kept
  // separate from text so the client knows to render the blurred category
  // placeholder.
  category: string | null;
  visibility?: Visibility;
};
export type SavedResponse = {
  itemId: string;
  rating: number;
  category: string | null;
  // null when the viewer can't see private text. Rating + category remain so
  // the blurred row can show which rating button was selected (the position,
  // not the digit) and the category badge.
  editedText: string | null;
  visibility?: Visibility;
  // "system" = a rating on a pre-populated event; "user" = a row the owner added
  // via "+Add another". Only "user" rows are genuine custom drafts — a "system"
  // response whose itemId is no longer in the pre-populated list is an ORPHAN
  // (the item list was regenerated by a re-score/reframe), not a custom row.
  source?: string;
};

type Props = {
  evaluationId: string;
  summary: string;
  prePopulated: RecItem[];
  savedResponses: SavedResponse[];
  // True when the current Clerk-authenticated user owns this evaluation
  // (verified via /claim/callback identity match). When false, the first
  // rating click opens the Claim Your Profile modal instead of saving.
  isOwner: boolean;
  // When the claim callback fails for GitHub or email (no high-confidence
  // identity signal), the welcome page passes this so the modal auto-opens
  // with a yellow banner steering the visitor to LinkedIn.
  initialBanner?: {
    kind: "claim_failed";
    provider: "github" | "email";
  } | null;
  firstName?: string | null;
};

const CATEGORY_OPTIONS = [
  "fundraising",
  "hiring",
  "intros",
  "tactical",
  "positioning",
  "wellbeing",
] as const;

const CATEGORY_COLOR: Record<string, string> = {
  fundraising: "text-emerald-400",
  hiring: "text-blue-400",
  intros: "text-violet-400",
  tactical: "text-amber-400",
  positioning: "text-pink-400",
  wellbeing: "text-zinc-400",
};

const RATING_LABELS = ["Unlikely", "Possibly", "Probably", "Definitely"] as const;

// Fillers used in the blurred non-owner view of a private row. Letter-shaped
// content (not solid blocks) so CSS blur renders as "blurred text" rather than
// a uniform white bar. Same string used for every private row so the real
// text length isn't leaked.
const BLUR_TEXT_FILLER =
  "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim";
const BLUR_CATEGORY_FILLER = "private";

function RatingButtons({
  value,
  onChange,
  disabled,
  blurred,
}: {
  value: number | null;
  onChange: (n: number | null) => void;
  disabled?: boolean;
  // When true, render the buttons non-interactive with blurred digits — used
  // for the non-owner view of a private row. The selected position still
  // shows the gold background so visitors can see *that* a rating exists,
  // but the digit itself isn't legible.
  blurred?: boolean;
}) {
  const [hovered, setHovered] = useState<number | null>(null);
  // Show hovered label first; fall back to currently-selected label when not hovering.
  const labelIdx = hovered ?? value ?? null;
  return (
    <div className="flex flex-col items-start sm:items-end gap-1 shrink-0">
      <div
        className={`flex gap-1 ${blurred ? "pointer-events-none select-none" : ""}`}
        onMouseLeave={() => setHovered(null)}
      >
        {[1, 2, 3, 4].map((n) => {
          const selected = value === n;
          return (
            <button
              key={n}
              type="button"
              aria-label={selected ? `Clear ${RATING_LABELS[n - 1]}` : RATING_LABELS[n - 1]}
              disabled={disabled || blurred}
              onClick={() => onChange(selected ? null : n)}
              onMouseEnter={() => setHovered(n)}
              // 36×36 on mobile (was 28×28) — clears the iOS minimum so
              // owners can actually tap a rating with a thumb on a phone.
              // Desktop stays compact at 28×28.
              className={`w-9 h-9 sm:w-7 sm:h-7 rounded-md font-mono text-sm sm:text-xs font-semibold transition-colors disabled:opacity-40 ${
                selected
                  ? "bg-[#dfa43a] text-black"
                  : "border border-zinc-700 text-zinc-400 hover:border-zinc-500 hover:text-zinc-100"
              } ${blurred ? "blur-[3px] cursor-default" : ""}`}
            >
              {n}
            </button>
          );
        })}
      </div>
      {/* Reserve the row so the layout doesn't jump when the label appears. */}
      <span className="text-[10px] uppercase tracking-[0.15em] text-zinc-400 h-3 leading-none">
        {!blurred && labelIdx ? RATING_LABELS[labelIdx - 1] : ""}
      </span>
    </div>
  );
}


type CustomDraft = {
  itemId: string;
  category: (typeof CATEGORY_OPTIONS)[number];
  text: string;
  rating: number | null;
};

async function saveRating(args: {
  evaluationId: string;
  itemId: string;
  rating: number;
  category?: string;
  text?: string;
}): Promise<boolean> {
  const res = await fetch("/api/recommendations", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(args),
  });
  return res.ok;
}

async function clearRating(evaluationId: string, itemId: string): Promise<boolean> {
  const res = await fetch("/api/recommendations", {
    method: "DELETE",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ evaluationId, itemId }),
  });
  return res.ok;
}

async function saveVisibility(args: {
  evaluationId: string;
  itemId: string;
  visibility: Visibility;
}): Promise<boolean> {
  const res = await fetch("/api/recommendations/visibility", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(args),
  });
  return res.ok;
}

function newCustomDraft(): CustomDraft {
  return {
    itemId: `custom-${Math.random().toString(36).slice(2, 10)}`,
    category: "tactical",
    text: "",
    rating: null,
  };
}

export function Recommendations({ evaluationId, summary, prePopulated, savedResponses, isOwner, initialBanner, firstName }: Props) {
  const [claimOpen, setClaimOpen] = useState(initialBanner?.kind === "claim_failed" && !isOwner);

  // Pull saved data into local state, keyed by item id.
  const savedById = new Map(savedResponses.map((r) => [r.itemId, r]));

  const [ratings, setRatings] = useState<Record<string, number | null>>(() => {
    const init: Record<string, number | null> = {};
    for (const item of prePopulated) {
      init[item.id] = savedById.get(item.id)?.rating ?? null;
    }
    return init;
  });

  // Visibility state — keyed by item id. Seeded from the server's
  // visibility on pre-populated items + saved responses (custom rows).
  const [visibility, setVisibility] = useState<Record<string, Visibility>>(() => {
    const init: Record<string, Visibility> = {};
    for (const item of prePopulated) {
      init[item.id] = item.visibility ?? "public";
    }
    for (const r of savedResponses) {
      if (r.visibility && r.visibility !== "public") init[r.itemId] = r.visibility;
    }
    return init;
  });

  // Hydrate custom drafts from saved responses the owner ACTUALLY added
  // (source "user") whose itemId isn't in the pre-populated set. A "system"
  // response not in the set is an ORPHAN — its pre-populated item was
  // regenerated (re-score/reframe) and got a new id — and must NOT render as a
  // phantom empty custom row (that's the /samuel-odio bug). Legacy rows with no
  // source recorded fall back to the old heuristic (treat slug-less custom ids
  // as user rows; orphaned system ids are slug-style and excluded).
  const prePopIds = new Set(prePopulated.map((p) => p.id));
  const isUserRow = (r: SavedResponse) =>
    r.source === "user" || (r.source == null && r.itemId.startsWith("custom-"));
  const initialCustomDrafts: CustomDraft[] = savedResponses
    .filter((r) => !prePopIds.has(r.itemId) && isUserRow(r))
    .map((r) => ({
      itemId: r.itemId,
      category:
        (CATEGORY_OPTIONS.find((c) => c === r.category) ?? "tactical") as
          (typeof CATEGORY_OPTIONS)[number],
      text: r.editedText ?? "",
      rating: r.rating,
    }));
  const [customs, setCustoms] = useState<CustomDraft[]>(
    initialCustomDrafts.length > 0 ? initialCustomDrafts : [newCustomDraft()],
  );

  async function rate(itemId: string, n: number | null, category: string) {
    // Visitor hasn't claimed this profile yet → show modal, don't save.
    if (!isOwner) {
      setClaimOpen(true);
      return;
    }
    setRatings((s) => ({ ...s, [itemId]: n }));
    if (n === null) {
      await clearRating(evaluationId, itemId);
    } else {
      await saveRating({ evaluationId, itemId, rating: n, category });
    }
  }

  async function rateCustom(draft: CustomDraft, n: number | null) {
    if (!isOwner) {
      setClaimOpen(true);
      return;
    }
    if (!draft.text.trim()) return; // need text before rating saves
    setCustoms((arr) => arr.map((d) => (d.itemId === draft.itemId ? { ...d, rating: n } : d)));
    if (n === null) {
      await clearRating(evaluationId, draft.itemId);
    } else {
      await saveRating({
        evaluationId,
        itemId: draft.itemId,
        rating: n,
        category: draft.category,
        text: draft.text.trim(),
      });
    }
  }

  async function toggleVisibility(itemId: string, next: Visibility) {
    if (!isOwner) {
      setClaimOpen(true);
      return;
    }
    setVisibility((s) => ({ ...s, [itemId]: next }));
    await saveVisibility({ evaluationId, itemId, visibility: next });
  }

  function updateCustom(itemId: string, patch: Partial<CustomDraft>) {
    setCustoms((arr) => arr.map((d) => (d.itemId === itemId ? { ...d, ...patch } : d)));
  }

  function addCustom() {
    setCustoms((arr) => [...arr, newCustomDraft()]);
  }

  function removeCustom(itemId: string) {
    setCustoms((arr) => arr.filter((d) => d.itemId !== itemId));
  }

  if (!summary && prePopulated.length === 0 && customs.length === 0) return null;

  return (
    <>
      <ClaimProfileModal
        open={claimOpen}
        onClose={() => setClaimOpen(false)}
        evaluationId={evaluationId}
        initialBanner={initialBanner ?? null}
        firstName={firstName}
      />
      <section className="w-full max-w-2xl flex flex-col gap-6 mt-4">
      <div className="border-t border-zinc-800 pt-8 flex flex-col gap-2">
        <p
          className="text-lg sm:text-xl font-bold"
          style={{ color: "#dfa43a" }}
        >
          What you likely need
        </p>
        {summary && (
          <p className="text-base sm:text-lg text-zinc-200 leading-relaxed">{summary}</p>
        )}
      </div>

      <div className="flex flex-col gap-2">
        <p
          className="text-lg sm:text-xl font-bold"
          style={{ color: "#dfa43a" }}
        >
          Would you attend these IRL Festival events?
        </p>
        <p className="text-base sm:text-lg text-zinc-100 leading-relaxed">
          We will tune and customize your Founder Festival experience to make sure
          you get invited to the events that would be most valuable to you.
        </p>
      </div>

      <ul className="flex flex-col gap-3">
        {prePopulated.map((item) => {
          // Non-owner viewing a row the owner marked private: server scrubs
          // `text` to null. Render a blurred placeholder + blurred rating
          // buttons; hide the slider entirely.
          const isHiddenFromViewer = item.text === null;
          return (
            <li
              key={item.id}
              className="flex flex-col gap-2 sm:flex-row sm:gap-3 sm:items-start text-sm sm:text-base text-zinc-300"
            >
              {isHiddenFromViewer ? (
                <span
                  aria-label="Private category"
                  className="text-[10px] uppercase tracking-[0.18em] font-medium shrink-0 sm:w-24 sm:pt-2 text-zinc-500 blur-[2px] select-none pointer-events-none"
                >
                  {BLUR_CATEGORY_FILLER}
                </span>
              ) : (
                <span
                  className={`text-[10px] uppercase tracking-[0.18em] font-medium shrink-0 sm:w-24 sm:pt-2 ${
                    item.category ? CATEGORY_COLOR[item.category] ?? "text-zinc-500" : "text-zinc-500"
                  }`}
                >
                  {item.category}
                </span>
              )}
              {isHiddenFromViewer ? (
                <span
                  aria-label="Private priority"
                  className="flex-1 min-w-0 sm:pt-1 blur-[4px] select-none pointer-events-none text-zinc-400"
                >
                  {BLUR_TEXT_FILLER}
                </span>
              ) : (
                <span className="flex-1 min-w-0 sm:pt-1">{item.text}</span>
              )}
              <div className="flex flex-col items-start sm:items-end gap-2">
                <RatingButtons
                  value={ratings[item.id] ?? null}
                  onChange={(n) => rate(item.id, n, item.category ?? "")}
                  blurred={isHiddenFromViewer}
                />
                {isOwner && (
                  <VisibilitySlider
                    value={visibility[item.id] ?? "public"}
                    onChange={(next) => toggleVisibility(item.id, next)}
                  />
                )}
                {!isOwner && (
                  // Non-owners still see a slider so they can discover the
                  // feature; clicking it opens the Claim Your Profile modal
                  // (mirrors the rating-button gate). Hidden on private rows
                  // since the row itself is being hidden from non-owners.
                  !isHiddenFromViewer && (
                    <VisibilitySlider
                      value="public"
                      onChange={(next) => toggleVisibility(item.id, next)}
                    />
                  )
                )}
              </div>
            </li>
          );
        })}

        {customs.map((draft) => {
          const savedRow = savedById.get(draft.itemId);
          const isHiddenFromViewer = savedRow?.visibility !== "public" && savedRow?.editedText === null;
          return (
            <li
              key={draft.itemId}
              className="flex flex-col gap-2 sm:flex-row sm:gap-3 sm:items-start text-sm sm:text-base text-zinc-300"
            >
              {isHiddenFromViewer ? (
                <span
                  aria-label="Private category"
                  className="text-[10px] uppercase tracking-[0.18em] font-medium shrink-0 sm:w-24 sm:pt-2 text-zinc-500 blur-[2px] select-none pointer-events-none"
                >
                  {BLUR_CATEGORY_FILLER}
                </span>
              ) : (
                <select
                  value={draft.category}
                  onChange={(e) =>
                    updateCustom(draft.itemId, {
                      category: e.target.value as (typeof CATEGORY_OPTIONS)[number],
                    })
                  }
                  className={`bg-transparent border border-zinc-700 rounded px-2 py-1 text-[10px] uppercase tracking-[0.18em] font-medium shrink-0 sm:w-24 ${
                    CATEGORY_COLOR[draft.category] ?? "text-zinc-500"
                  }`}
                >
                  {CATEGORY_OPTIONS.map((c) => (
                    <option key={c} value={c} className="bg-[#1c1c1c] text-zinc-100">
                      {c}
                    </option>
                  ))}
                </select>
              )}
              {isHiddenFromViewer ? (
                <span
                  aria-label="Private priority"
                  className="flex-1 min-w-0 sm:pt-1 blur-[4px] select-none pointer-events-none text-zinc-400"
                >
                  {BLUR_TEXT_FILLER}
                </span>
              ) : (
                <input
                  value={draft.text}
                  onChange={(e) => updateCustom(draft.itemId, { text: e.target.value })}
                  placeholder="What other events would you like to participate in?"
                  className="flex-1 min-w-0 bg-transparent border-b border-zinc-700 focus:border-zinc-400 outline-none px-1 py-1 text-zinc-100"
                />
              )}
              {/* Rating buttons + remove grouped so they stay on one line when the
                  row stacks vertically on mobile. gap-1 matches the old ml-1 so
                  desktop spacing is unchanged. */}
              <div className="flex items-start gap-1">
                <div className="flex flex-col items-start sm:items-end gap-2">
                  <RatingButtons
                    value={draft.rating}
                    onChange={(n) => rateCustom(draft, n)}
                    disabled={!draft.text.trim() && !isHiddenFromViewer}
                    blurred={isHiddenFromViewer}
                  />
                  {isOwner && (
                    <VisibilitySlider
                      value={visibility[draft.itemId] ?? "public"}
                      onChange={(next) => toggleVisibility(draft.itemId, next)}
                      disabled={!draft.text.trim()}
                    />
                  )}
                  {!isOwner && !isHiddenFromViewer && (
                    <VisibilitySlider
                      value="public"
                      onChange={(next) => toggleVisibility(draft.itemId, next)}
                    />
                  )}
                </div>
                {!isHiddenFromViewer && (
                  // 36×36 hit area on mobile, smaller on desktop where the
                  // ✕ sits inline next to a tight row.
                  <button
                    type="button"
                    onClick={() => removeCustom(draft.itemId)}
                    className="inline-flex items-center justify-center w-9 h-9 sm:w-auto sm:h-auto sm:px-1 sm:py-1 text-zinc-500 hover:text-zinc-200 text-base sm:text-sm shrink-0"
                    aria-label="Remove row"
                    title="Remove"
                  >
                    ✕
                  </button>
                )}
              </div>
            </li>
          );
        })}
      </ul>

      <button
        type="button"
        onClick={addCustom}
        className="self-start text-sm text-zinc-400 hover:text-zinc-100 transition-colors"
      >
        + Add another
      </button>
      </section>
    </>
  );
}
